const FILTER_BY_FRIENDS: string = 'FILTER_FRIENDS'
const FILTER_BY_GROUPS: string = 'FILTER_GROUPS'
const FILTER_BY_COLOR_AVATAR: string = 'FILTER_BY_COLOR_AVATAR'
const UPDATE_STORE: string = 'UPDATE_STORE'

export default {
	FILTER_BY_FRIENDS,
	FILTER_BY_GROUPS,
	FILTER_BY_COLOR_AVATAR,
	UPDATE_STORE,
}